<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="59986" started-at="2018-09-10T09:17:57Z" finished-at="2018-09-10T09:18:57Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="59986" started-at="2018-09-10T09:17:57Z" finished-at="2018-09-10T09:18:57Z">
      <class name="com.dice.FirstTest">
        <test-method status="PASS" signature="methodSetUp()[pri:0, instance:com.dice.FirstTest@783e6358]" name="methodSetUp" is-config="true" duration-ms="2383" started-at="2018-09-10T09:18:31Z" finished-at="2018-09-10T09:18:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="PASS" signature="firstTestMethod()[pri:0, instance:com.dice.FirstTest@783e6358]" name="firstTestMethod" duration-ms="22104" started-at="2018-09-10T09:18:34Z" finished-at="2018-09-10T09:18:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTestMethod -->
        <test-method status="PASS" signature="methodTearDown()[pri:0, instance:com.dice.FirstTest@783e6358]" name="methodTearDown" is-config="true" duration-ms="931" started-at="2018-09-10T09:18:56Z" finished-at="2018-09-10T09:18:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
      </class> <!-- com.dice.FirstTest -->
      <class name="com.dice.LoginTest">
        <test-method status="SKIP" signature="negativeTest(java.util.Map)[pri:0, instance:com.dice.LoginTest@4e04a765]" name="negativeTest" duration-ms="0" started-at="2018-09-10T09:18:02Z" data-provider="CsvDataProvider" finished-at="2018-09-10T09:18:02Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.RuntimeException: File src/test/resources/test_data/LoginTest_negativeTest.csv was not found.
[Ljava.lang.StackTraceElement;@741a8937]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: File src/test/resources/test_data/LoginTest_negativeTest.csv was not found.
[Ljava.lang.StackTraceElement;@741a8937
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.RuntimeException: File src/test/resources/test_data/LoginTest_negativeTest.csv was not found.
[Ljava.lang.StackTraceElement;@741a8937
at com.dice.base.CsvDataProvider.provideData(CsvDataProvider.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeTest -->
        <test-method status="PASS" signature="methodSetUp()[pri:0, instance:com.dice.LoginTest@4e04a765]" name="methodSetUp" is-config="true" duration-ms="2499" started-at="2018-09-10T09:18:02Z" finished-at="2018-09-10T09:18:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="PASS" signature="positiveTest()[pri:0, instance:com.dice.LoginTest@4e04a765]" name="positiveTest" duration-ms="26157" started-at="2018-09-10T09:18:04Z" finished-at="2018-09-10T09:18:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
        <test-method status="PASS" signature="methodTearDown()[pri:0, instance:com.dice.LoginTest@4e04a765]" name="methodTearDown" is-config="true" duration-ms="868" started-at="2018-09-10T09:18:30Z" finished-at="2018-09-10T09:18:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
      </class> <!-- com.dice.LoginTest -->
      <class name="com.dice.SecondTest">
        <test-method status="PASS" signature="methodSetUp()[pri:0, instance:com.dice.SecondTest@13fee20c]" name="methodSetUp" is-config="true" duration-ms="3724" started-at="2018-09-10T09:17:57Z" finished-at="2018-09-10T09:18:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="PASS" signature="secondTestMethod()[pri:0, instance:com.dice.SecondTest@13fee20c]" name="secondTestMethod" duration-ms="386" started-at="2018-09-10T09:18:00Z" finished-at="2018-09-10T09:18:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTestMethod -->
        <test-method status="PASS" signature="methodTearDown()[pri:0, instance:com.dice.SecondTest@13fee20c]" name="methodTearDown" is-config="true" duration-ms="864" started-at="2018-09-10T09:18:01Z" finished-at="2018-09-10T09:18:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
      </class> <!-- com.dice.SecondTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
